package co.orange.domain.enums

enum class BankType(val displayName: String, val code: String) {
    HANA("하나은행", "081"),
    SHINHAN("신한은행", "088"),
    KOREA_BANK("한국은행", "001"),
    KDB("KDB산업은행", "002"),
    IBK("IBK기업은행", "003"),
    KOOKMIN("국민은행", "004"),
    NONGHYUP_BANK("농협은행", "011"),
    NONGHYUP_MEMBER("농협회원조합", "012"),
    WOORI("우리은행", "020"),
    POST("우체국", "071"),
    SC("SC제일은행", "023"),
    CITI("한국씨티은행", "027"),
    DAEGU("대구은행", "031"),
    BUSAN("부산은행", "032"),
    GWANGJU("광주은행", "034"),
    JEJU("제주은행", "035"),
    JEONBUK("전북은행", "037"),
    KYONGNAM("경남은행", "039"),
    FOREIGN_EXCHANGE("외환은행", "005"),
    SUHYUP("수협중앙회", "007"),
    KEXIM("수출입은행", "008"),
    SAE_MAUL("새마을금고연합회", "045"),
    SHINHYUP("신협중앙회", "048"),
    SAVING("상호저축은행", "050"),
    MORGAN_STANLEY("모건스탠리은행", "052"),
    HSBC("HSBC은행", "054"),
    DEUTSCHE("도이치은행", "055"),
    ABN_AMRO("에이비엔암로은행", "056"),
    JP_MORGAN("제이피모간체이스은행", "057"),
    MIZUHO("미즈호코퍼레이트은행", "058"),
    MITSUBISHI_UFJ("미쓰비시도쿄UFJ은행", "059"),
    BOA("BOA", "060"),
    CREDIT_GUARANTEE("신용보증기금", "076"),
    TECH_CREDIT_GUARANTEE("기술신용보증기금", "077"),
    KOREA_HOUSING_FINANCE("한국주택금융공사", "093"),
    SEOUL_GUARANTEE("서울보증보험", "094"),
    POLICE_AGENCY("경찰청", "095"),
    KFTC("금융결제원", "099"),
    DONGYANG_SEC("동양종합금융증권", "209"),
    HYUNDAI_SEC("현대증권", "218"),
    MIRAE_ASSET("미래에셋증권", "230"),
    DAEWOO_SEC("대우증권", "238"),
    SAMSUNG_SEC("삼성증권", "240"),
    KOREA_INVESTMENT("한국투자증권", "243"),
    WOORI_INVESTMENT("우리투자증권", "247"),
    KYOBO_SEC("교보증권", "261"),
    HI_INVESTMENT("하이투자증권", "262"),
    HMC_INVESTMENT("에이치엠씨투자증권", "263"),
    KIWOOM("키움증권", "264"),
    ETRADE("이트레이드증권", "265"),
    SK_SEC("에스케이증권", "266"),
    DAE_SHIN_SEC("대신증권", "267"),
    SOLOMON_INVESTMENT("솔로몬투자증권", "268"),
    HANWHA_INVESTMENT("한화투자증권", "269"),
    HANA_INVESTMENT("하나대투증권", "270"),
    GOODMORNING_SHINHAN("굿모닝신한증권", "278"),
    DONG_BU_SEC("동부증권", "279"),
    EUGENE_INVESTMENT("유진투자증권", "280"),
    MERITZ_SEC("메리츠증권", "287"),
    NH_INVESTMENT("엔에이치투자증권", "289"),
    BUKOOK_SEC("부국증권", "290"),
    SHINYOUNG_SEC("신영증권", "291"),
    LIG_INVESTMENT("엘아이지투자증권", "292"),
    ;

    companion object {
        fun fromCode(code: String): String? {
            return values().find { it.code == code }?.displayName
        }
    }
}
